### ISSUE TITLE
Debug Fee related object loading on OccPeriod

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#3] opened 2019-12-06 03:30 UTC
Thanks to NADGIT, we have mostly functional fee infrastructure for Beta v.0.9. Loading the Payment list and Fee List on OccPayment produces Errors. Please debug by uncommenting the following lines in OccupancyIntegrator.java

```
//        op.setPaymentList(pai.getPaymentList(op));
//        op.setFeeList(pai.getFeeAssigned(op));
```

## Payments goals

- We want to be able to make payments against fees associated with OccPeriods. That will be managed on a page called occPeriodPayments.xhtml (which as of 17 DEC only exists on the branch called betawip_branchreorg
- Consider approaches to unifying Payments across Occ and CE. Perhaps some sort of Enum like EventDomainEnum on the event side
- Test and debug payments and fees associated with Code Enforcement cases. Possible logic: Fees can be associated with CodeViolations. When a violation containing a fee is added to a CodeEnforcement case, that fee gets attached to the Case itself, and is managed just like fees associated with an OccPeriod

For reference, here's the new Event structure to cope with dual functionality in both Occ and CE
```
public  class       Event 
        extends     BOb
        implements  Comparable<Event> {
    
    protected int eventID;
    protected EventCategory category;
    
    protected EventDomainEnum domain;
    
    protected int ceCaseID;
    protected int occPeriodID;
```

**Comment by NADGIT** [comment] 2019-12-16 15:49
Alright! I'm gonna fix this and also make sure that my integrator is still compatible with the new SQL tables.

**Comment by NADGIT** [comment] 2019-12-18 15:35
Updated the SQL, I'm fixing those two loading methods now

**Comment by NADGIT** [comment] 2019-12-18 16:41
The loading methods no longer throw errors. I suspect the errors were probably caused by the outdated SQL.

**Comment by NADGIT** [comment] 2019-12-19 21:36
Before I got started breaking new ground with the CECase stuff, I restored the payment UI back to its former functional glory. You can now assign payments, fees, etc. Also, the FeeAssigned objects use polymorphism and the EventDomainEnum like we talked about. I just pushed the commit up, you can see the UI on occPeriodPayments.xhtml.

**Comment by NADGIT** [comment] 2019-12-19 21:50
By the way, I was looking at the graph you drew again and I just remembered: I already have fee and payment management pages that should _theoretically_ be able to manage both CE and Occ fees and payments, I just haven't added the ability to edit CE stuff. The pages are feeManage.xhtml and paymentManage.xhtml. I'll add the functionality once I've planned it all out.

**Comment by NADGIT** [comment] 2020-01-16 14:16
I have completed almost all the code for Assigned Fee Management, Fee Permissions Management, And Payment Management. The only feature left is that CE Case Fees do not autoassign yet, but first I want to test and debug the existing life cycle since the interface is acting strangely: Though the database is being updated just fine, the UI doesn't always have the right data.

**Comment by NADGIT** [comment] 2020-03-12 15:47
I actually fixed this issue a while ago (take a look at the PaymentsPostRecovery branch pull request and commit history for more details), but forgot to close it. I'm closing it now.

**Closed by NADGIT** 2020-03-12 15:47 UTC
Labels: payments
